ghostHost: blog.aikashev.tk

mariadb:
   master:
    persistence:
      size: 1Gi

service:
  type: ClusterIP
  
persistence:
  size: 1Gi

resources:
  requests:
    memory: 100Mi
    cpu: 100m

ingress:
  enabled: "true"

  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

  hosts:
  - name: blog.aikashev.tk
    tls: "true"
    tlsHosts: 
    - blog.aikashev.tk
    tlsSecret: blog.aikashev.tk-tls
