controller:
  publishService:
    enabled: "true"
  stats:
    enabled: "true"
  metrics:
    enabled: "true"
    service:
      annotations:
       prometheus.io/scrape: "true"
       prometheus.io/port: "10254"

  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.aikashev.tk,aikashev.tk"
